spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db1?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  tomcat:
    uri-encoding: UTF-8
